version: "3.9"

services:

  api:
    build: .
    container_name: bot_api
    env_file:
      - .env
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - bot
    ports:
      - "8000:8000"
    networks:
      - shared-network

  bot:
    build: .
    container_name: bot_worker
    env_file:
      - .env
    command: >
      python -m app.bot.runner
    networks:
      - shared-network

networks:
  shared-network:
    external: true
